services:
  # API - Development overrides for enhanced debugging
  api:
    environment:
      # Enhanced logging for development
      - Logging__LogLevel__Default=${LOG_LEVEL_DEFAULT:-Debug}
      - Logging__LogLevel__Microsoft.AspNetCore=${LOG_LEVEL_ASPNETCORE:-Information}
      - Logging__LogLevel__Microsoft.EntityFrameworkCore.Database.Command=Information
      - Logging__LogLevel__Microsoft.EntityFrameworkCore.Database.Connection=Information

  # Admin - Development overrides for enhanced debugging
  admin:
    environment:
      # Enhanced logging for development
      - Logging__LogLevel__Default=${LOG_LEVEL_DEFAULT:-Debug}
      - Logging__LogLevel__Microsoft.AspNetCore=${LOG_LEVEL_ASPNETCORE:-Information}
