using System.ComponentModel.DataAnnotations;

namespace StadiumDrinkOrdering.Shared.Models;

/// <summary>
/// The raw bytes of an event's poster image, held in a table of its own rather than as a column on
/// <see cref="Event"/>.
///
/// EF Core has no way to leave a single column unloaded, so an inline <c>byte[]</c> would pull a
/// multi-megabyte poster into every <c>Events.ToListAsync()</c> — including the admin events grid,
/// which only needs to know whether a poster exists. Splitting the blob out keeps those queries
/// cheap: the "has a poster" flag and the display metadata live on <see cref="Event"/>
/// (<c>PosterContentType</c>, <c>PosterWidth</c>, <c>PosterHeight</c>), and these bytes are read
/// only by the endpoint that serves the image.
/// </summary>
public class EventPoster
{
    public int Id { get; set; }

    /// <summary>Owning event. Unique — an event has at most one poster.</summary>
    public int EventId { get; set; }

    public Event? Event { get; set; }

    /// <summary>The encoded image (PNG as returned by the image-generation API).</summary>
    public byte[] ImageData { get; set; } = Array.Empty<byte>();

    /// <summary>
    /// A downscaled JPEG of <see cref="ImageData"/>, produced in the admin browser at generation
    /// time. The customer fixture strip renders up to 20 cards, so serving the ~2 MB originals
    /// there would cost tens of megabytes on mobile; this variant is a few tens of KB. Null for
    /// posters saved before thumbnails existed — callers fall back to the full image.
    /// </summary>
    public byte[]? ThumbnailData { get; set; }

    /// <summary>MIME type of <see cref="ThumbnailData"/> (image/jpeg), or null when there is none.</summary>
    public string? ThumbnailContentType { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Canonical description of the facts an event poster bakes into its pixels.
///
/// Shared so the admin (which stamps the signature at generation time) and the API (which compares
/// it against the event's current values) cannot drift apart. If these strings differ, the artwork
/// is showing details the event no longer has.
/// </summary>
public static class PosterSignature
{
    /// <summary>
    /// Builds the signature from the volatile facts: the two teams and the kick-off, rendered to
    /// the minute in invariant form (the poster prints a date and time, so rescheduling either must
    /// count as a change).
    ///
    /// The venue is deliberately excluded even though it is printed on the poster: every event in
    /// this system is held at the single configured stadium, so it cannot change per fixture, and
    /// including it would force every caller to resolve the venue just to compare two strings.
    /// Renaming the venue is a rare admin action; posters can be regenerated by hand then.
    /// </summary>
    public static string For(string? homeTeam, string? awayTeam, DateTime kickOff)
    {
        static string Norm(string? s) => (s ?? string.Empty).Trim().ToLowerInvariant();
        return string.Join('|',
            Norm(homeTeam),
            Norm(awayTeam),
            kickOff.ToString("yyyy-MM-ddTHH:mm", System.Globalization.CultureInfo.InvariantCulture));
    }
}

// The former `TeamCrest` cache (a crest keyed by away-team name, created only as a by-product of
// building a fixture) has been replaced by the first-class `Team` directory entry — see Team.cs.
// Its rows were copied across by the AddTeamsDirectory migration.
